import type { FactoryFormValues } from "../schemas/factory-schema";

export const SEED_FACTORIES: FactoryFormValues[] = [
  {
    name: "HTX Chè Shan tuyết Vị Xuyên",
    organizationType: "COOPERATIVE",
    taxCode: "5100123456",
    foundedYear: 2015,
    representative: { fullName: "Nguyễn Thị Hoa", gender: "FEMALE", phone: "0912345678", email: "hoa.htx@gmail.com" },
    location: { provinceCode: "TQ", wardCode: "TQ-VX", address: "Thôn Nậm Ngặt", latitude: 22.67, longitude: 104.98 },
    productGroupIds: ["TEA"],
    services: ["PRE_PROCESSING", "DRYING", "PACKAGING"],
    description: "Chế biến chè Shan tuyết theo tiêu chuẩn hữu cơ, có xưởng sấy và đóng gói.",
    offersExternalCapacity: true,
    machines: [
      { id: "m-1", name: "Máy sấy chè", functions: ["DRYING"], productGroupIds: ["TEA"], maxCapacity: 800, capacityUnit: "KG_PER_DAY", status: "ACTIVE" },
    ],
    hasCertification: true,
    certifications: [{ id: "c-1", type: "FOOD_SAFETY", number: "ATTP-2024-001", issuedDate: "2024-03-01", expiryDate: "2027-03-01", issuer: "DARD" }],
    avatarUrl: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=200",
    facilityPhotos: [
      "https://images.unsplash.com/photo-1582793988951-9aed5509eb97?w=400",
      "https://images.unsplash.com/photo-1523920290228-4f321a939b4c?w=400",
    ],
    machinePhotos: [],
  },
  {
    name: "Công ty TNHH Nông sản Đoan Hùng",
    organizationType: "ENTERPRISE",
    taxCode: "2600987654",
    foundedYear: 2018,
    representative: { fullName: "Trần Văn Nam", gender: "MALE", phone: "0987654321", email: "" },
    location: { provinceCode: "PT", wardCode: "PT-DH", address: "Khu CN Đoan Hùng", latitude: undefined, longitude: undefined },
    productGroupIds: ["FRUIT"],
    services: ["WASHING", "SORTING", "STORAGE"],
    description: "Kho lạnh và dây chuyền phân loại bưởi.",
    offersExternalCapacity: false,
    machines: [],
    hasCertification: false,
    certifications: [],
    avatarUrl: "",
    facilityPhotos: [],
    machinePhotos: [],
  },
  {
    name: "Hộ kinh doanh Dược liệu Sa Pa",
    organizationType: "HOUSEHOLD_BUSINESS",
    taxCode: "",
    foundedYear: 2020,
    representative: { fullName: "Lò Thị Mai", gender: "FEMALE", phone: "0971112233", email: "" },
    location: { provinceCode: "LC", wardCode: "LC-SP", address: "Tổ 5, Sa Pa", latitude: 22.34, longitude: 103.84 },
    productGroupIds: ["HERB", "SPICE"],
    services: ["DRYING", "GRINDING"],
    description: "Sấy, nghiền dược liệu và gừng.",
    offersExternalCapacity: true,
    machines: [
      { id: "m-2", name: "Máy nghiền bột", functions: ["GRINDING"], productGroupIds: ["HERB", "SPICE"], maxCapacity: 50, capacityUnit: "KG_PER_HOUR", status: "MAINTENANCE" },
    ],
    hasCertification: false,
    certifications: [],
    avatarUrl: "",
    facilityPhotos: [],
    machinePhotos: [],
  },
  {
    name: "Công ty CP Thực phẩm Tam Điệp",
    organizationType: "ENTERPRISE",
    taxCode: "2700456789",
    foundedYear: 2012,
    representative: { fullName: "Phạm Thị Thu", gender: "FEMALE", phone: "0973456123", email: "thu.pham@tamdiepfood.vn" },
    location: { provinceCode: "NB", wardCode: "NB-TD", address: "KCN Tam Điệp", latitude: 20.16, longitude: 105.92 },
    productGroupIds: ["FRUIT", "VEGETABLE"],
    services: ["WASHING", "PRESSING", "PACKAGING", "STORAGE"],
    description: "Dây chuyền ép nước trái cây và chiết chai, kho mát 200 m².",
    offersExternalCapacity: true,
    machines: [
      { id: "m-3", name: "Dây chuyền ép dứa", functions: ["WASHING", "PRESSING"], productGroupIds: ["FRUIT"], maxCapacity: 2, capacityUnit: "TON_PER_DAY", status: "ACTIVE" },
      { id: "m-4", name: "Máy chiết rót đóng chai", functions: ["PACKAGING"], productGroupIds: ["FRUIT", "VEGETABLE"], maxCapacity: 500, capacityUnit: "KG_PER_HOUR", status: "ACTIVE" },
    ],
    hasCertification: true,
    certifications: [{ id: "c-2", type: "HACCP", number: "HACCP-VN-2024-0156", issuedDate: "2024-05-10", expiryDate: "2027-05-10", issuer: "QUACERT" }],
    avatarUrl: "",
    facilityPhotos: [],
    machinePhotos: [],
  },
  {
    name: "Kho lạnh Việt Trì",
    organizationType: "ENTERPRISE",
    taxCode: "2600111222",
    foundedYear: 2020,
    representative: { fullName: "Lê Quang Huy", gender: "MALE", phone: "0915222333", email: "" },
    location: { provinceCode: "PT", wardCode: "PT-VT", address: "Đường Hùng Vương, Việt Trì", latitude: 21.32, longitude: 105.4 },
    productGroupIds: ["FRUIT", "VEGETABLE"],
    services: ["SORTING", "STORAGE"],
    description: "Cho thuê kho lạnh 0–5°C, phân loại quả trước khi nhập kho.",
    offersExternalCapacity: true,
    machines: [
      { id: "m-5", name: "Kho lạnh số 1", functions: ["STORAGE"], productGroupIds: ["FRUIT", "VEGETABLE"], maxCapacity: 20, capacityUnit: "TON_PER_DAY", status: "ACTIVE" },
    ],
    hasCertification: false,
    certifications: [],
    avatarUrl: "",
    facilityPhotos: [],
    machinePhotos: [],
  },
  {
    name: "Xưởng sấy nông sản Hà Giang",
    organizationType: "HOUSEHOLD_BUSINESS",
    taxCode: "",
    foundedYear: 2019,
    representative: { fullName: "Vàng Thị Dua", gender: "FEMALE", phone: "0386444555", email: "" },
    location: { provinceCode: "TQ", wardCode: "TQ-HG", address: "Tổ 3, phường Hà Giang 1", latitude: 22.82, longitude: 104.98 },
    productGroupIds: ["TEA", "HERB"],
    services: ["DRYING", "PACKAGING"],
    description: "Sấy lạnh chè, dược liệu quy mô nhỏ.",
    offersExternalCapacity: true,
    machines: [
      { id: "m-6", name: "Máy sấy lạnh", functions: ["DRYING"], productGroupIds: ["TEA", "HERB"], maxCapacity: 300, capacityUnit: "KG_PER_DAY", status: "ACTIVE" },
    ],
    hasCertification: true,
    certifications: [{ id: "c-3", type: "FOOD_SAFETY", number: "ATTP-2022-088", issuedDate: "2022-01-01", expiryDate: "2025-01-01", issuer: "DOH" }],
    avatarUrl: "",
    facilityPhotos: [],
    machinePhotos: [],
  },
];
