import type { FactoryFormValues } from "../schemas/factory-schema";

export const SEED_FACTORIES: FactoryFormValues[] = [
  {
    name: "HTX Chè Shan tuyết Vị Xuyên",
    organizationType: "COOPERATIVE",
    taxCode: "5100123456",
    foundedYear: 2015,
    representative: { fullName: "Nguyễn Thị Hoa", gender: "FEMALE", phone: "0912345678", email: "hoa.htx@gmail.com" },
    location: { provinceCode: "TQ", wardCode: "TQ-VX", address: "Thôn Nậm Ngặt", latitude: 22.67, longitude: 104.98 },
    productGroupIds: ["TEA"],
    services: ["PRE_PROCESSING", "DRYING", "PACKAGING"],
    description: "Chế biến chè Shan tuyết theo tiêu chuẩn hữu cơ, có xưởng sấy và đóng gói.",
    offersExternalCapacity: true,
    machines: [
      { id: "m-1", name: "Máy sấy chè", functions: ["DRYING"], productGroupIds: ["TEA"], maxCapacity: 800, capacityUnit: "KG_PER_DAY", availableCapacity: 300, availableFrom: "", availableTo: "", status: "ACTIVE" },
    ],
    hasCertification: true,
    certifications: [{ id: "c-1", type: "FOOD_SAFETY", number: "ATTP-2024-001", issuedDate: "2024-03-01", expiryDate: "2027-03-01", issuer: "DARD" }],
    avatarUrl: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=200",
    facilityPhotos: [
      "https://images.unsplash.com/photo-1582793988951-9aed5509eb97?w=400",
      "https://images.unsplash.com/photo-1523920290228-4f321a939b4c?w=400",
    ],
    machinePhotos: [],
  },
  {
    name: "Công ty TNHH Nông sản Đoan Hùng",
    organizationType: "ENTERPRISE",
    taxCode: "2600987654",
    foundedYear: 2018,
    representative: { fullName: "Trần Văn Nam", gender: "MALE", phone: "0987654321", email: "" },
    location: { provinceCode: "PT", wardCode: "PT-DH", address: "Khu CN Đoan Hùng", latitude: undefined, longitude: undefined },
    productGroupIds: ["FRUIT"],
    services: ["WASHING", "SORTING", "STORAGE"],
    description: "Kho lạnh và dây chuyền phân loại bưởi.",
    offersExternalCapacity: false,
    machines: [],
    hasCertification: false,
    certifications: [],
    avatarUrl: "",
    facilityPhotos: [],
    machinePhotos: [],
  },
  {
    name: "Hộ kinh doanh Dược liệu Sa Pa",
    organizationType: "HOUSEHOLD_BUSINESS",
    taxCode: "",
    foundedYear: 2020,
    representative: { fullName: "Lò Thị Mai", gender: "FEMALE", phone: "0971112233", email: "" },
    location: { provinceCode: "LC", wardCode: "LC-SP", address: "Tổ 5, Sa Pa", latitude: 22.34, longitude: 103.84 },
    productGroupIds: ["HERB", "SPICE"],
    services: ["DRYING", "GRINDING"],
    description: "Sấy, nghiền dược liệu và gừng.",
    offersExternalCapacity: true,
    machines: [
      { id: "m-2", name: "Máy nghiền bột", functions: ["GRINDING"], productGroupIds: ["HERB", "SPICE"], maxCapacity: 50, capacityUnit: "KG_PER_HOUR", availableCapacity: 0, availableFrom: "", availableTo: "", status: "MAINTENANCE" },
    ],
    hasCertification: false,
    certifications: [],
    avatarUrl: "",
    facilityPhotos: [],
    machinePhotos: [],
  },
];
