import type { MachineFormValues } from "../schemas/factory-schema";
import type { FactorySeedValues } from "../utils/factory-status";

// ─── Seed data ──────────────────────────────────────────────────────────────
// Company name, tax code (MST) and address come from the public business
// registry (masothue.com / thuvienphapluat.vn), with the 2025 province/ward
// merger applied. Representatives, phones, machines, capacities and
// certificate numbers are SAMPLE data — not the companies' real figures.
//
// Ids are positional: SEED_FACTORIES[i] → `f-${i + 1}`. Machine ids (m-*) are
// referenced by schedule.store, connection.api and certificate.mock.

const img = (id: string, w = 400) => `https://images.unsplash.com/${id}?w=${w}`;

const TEA_PHOTOS = [
  img("photo-1582793988951-9aed5509eb97"),
  img("photo-1523920290228-4f321a939b4c"),
  img("photo-1564890369478-c89ca6d9cde9"),
];
const FRUIT_PHOTOS = [
  img("photo-1610832958506-aa56368176cf"),
  img("photo-1619566636858-adf3ef46400b"),
  img("photo-1557800636-894a64c1696f"),
];
const COFFEE_PHOTOS = [
  img("photo-1447933601403-0c6688de566e"),
  img("photo-1611854779393-1b2da9d400fe"),
  img("photo-1559056199-641a0ac8b55e"),
];
const GRAIN_PHOTOS = [
  img("photo-1586201375761-83865001e31c"),
  img("photo-1536304993881-ff6e9eefa2a6"),
];
const VEG_PHOTOS = [
  img("photo-1540420773420-3366772f4999"),
  img("photo-1566385101042-1a0aa0c1268c"),
];
const HERB_PHOTOS = [
  img("photo-1471193945509-9ad0617afabf"),
  img("photo-1509358271058-acd22cc93898"),
];
const MACHINE_PHOTOS = [
  img("photo-1581091226825-a6a2a5aee158"),
  img("photo-1537462715879-360eeb61a0ad"),
  img("photo-1567789884554-0b844b597180"),
  img("photo-1513828583688-c52646db42da"),
  img("photo-1504917595217-d4dc5ebe6122"),
  img("photo-1586528116311-ad8dd3c8310d"),
];

type SeedMachine = Omit<MachineFormValues, "factoryId" | "certificateIds"> & {
  id: string;
};
const machine = (
  id: string,
  name: string,
  functions: string[],
  productGroupIds: string[],
  maxCapacity: number,
  capacityUnit: MachineFormValues["capacityUnit"],
  status: MachineFormValues["status"] = "ACTIVE",
): SeedMachine =>
  ({
    id,
    name,
    functions,
    productGroupIds,
    maxCapacity,
    capacityUnit,
    status,
  }) as SeedMachine;

export const SEED_FACTORIES: FactorySeedValues[] = [
  // f-1
  {
    name: "Hợp tác xã Chè Shan tuyết Cao Bồ",
    organizationType: "COOPERATIVE",
    taxCode: "5100478159",
    foundedYear: 2016,
    representative: {
      fullName: "Nguyễn Thị Hoa",
      gender: "FEMALE",
      phone: "0912345678",
      email: "htxchecaobo@gmail.com",
    },
    location: {
      provinceCode: "TQ",
      wardCode: "TQ-CB",
      address: "Thôn Bản Dâng",
      latitude: 22.7547,
      longitude: 104.8611,
    },
    productGroupIds: ["TEA"],
    services: ["PRE_PROCESSING", "DRYING", "ROASTING", "PACKAGING"],
    description:
      "HTX chế biến chè Shan tuyết cổ thụ vùng Tây Côn Lĩnh: hồng trà, bạch trà, chè xanh sao suốt. Nguyên liệu thu mua từ hơn 200 hộ đồng bào Dao, sản phẩm đạt OCOP 4 sao.",
    offersExternalCapacity: true,
    machines: [
      machine(
        "m-1",
        "Máy sấy chè Shan tuyết",
        ["DRYING"],
        ["TEA"],
        24,
        "TON_PER_MONTH",
      ),
      machine(
        "m-2",
        "Tôn sao chè (chảo quay)",
        ["ROASTING"],
        ["TEA"],
        9,
        "TON_PER_MONTH",
      ),
    ],
    hasCertification: true,
    certifications: [
      {
        id: "c-1",
        type: "FOOD_SAFETY",
        number: "58/2024/NNPTNT-HG",
        issuedDate: "2024-03-01",
        expiryDate: "2027-03-01",
        issuer: "DARD",
      },
      {
        id: "c-2",
        type: "OTHER",
        number: "OCOP-HG-2023-112",
        issuedDate: "2023-11-15",
        expiryDate: "2026-11-15",
        issuer: "DARD",
      },
    ],
    avatarUrl: img("photo-1564890369478-c89ca6d9cde9", 200),
    facilityPhotos: TEA_PHOTOS,
    machinePhotos: MACHINE_PHOTOS.slice(0, 3),
  },
  // f-2
  {
    name: "Công ty Cổ phần Chè Mỹ Lâm",
    organizationType: "ENTERPRISE",
    taxCode: "5000193784",
    foundedYear: 1995,
    representative: {
      fullName: "Trần Văn Nam",
      gender: "MALE",
      phone: "0987654321",
      email: "",
    },
    location: {
      provinceCode: "TQ",
      wardCode: "TQ-ML",
      address: "Tổ dân phố Lập Thành",
      latitude: 21.8906,
      longitude: 105.2211,
    },
    productGroupIds: ["TEA"],
    services: ["WASHING", "DRYING", "SORTING", "PACKAGING"],
    description:
      "Nhà máy chè đen OTD và chè xanh xuất khẩu, vùng nguyên liệu chè Trung du, LDP1 tại Yên Sơn.",
    offersExternalCapacity: true,
    machines: [
      machine(
        "m-3",
        "Dây chuyền chè đen OTD",
        ["WASHING", "DRYING"],
        ["TEA"],
        120,
        "TON_PER_MONTH",
      ),
      machine(
        "m-4",
        "Máy sàng phân loại chè",
        ["SORTING"],
        ["TEA"],
        90,
        "TON_PER_MONTH",
      ),
    ],
    hasCertification: true,
    certifications: [
      {
        id: "c-3",
        type: "HACCP",
        number: "HACCP-TQ-2023-0412",
        issuedDate: "2023-08-20",
        expiryDate: "2026-08-20",
        issuer: "QUACERT",
      },
    ],
    avatarUrl: "",
    facilityPhotos: TEA_PHOTOS.slice(0, 2),
    machinePhotos: MACHINE_PHOTOS.slice(2, 4),
  },
  // f-3
  {
    name: "Công ty TNHH Một thành viên Chè Hà Tuyên",
    organizationType: "ENTERPRISE",
    taxCode: "5000832864",
    foundedYear: 2012,
    representative: {
      fullName: "Hoàng Văn Thắng",
      gender: "MALE",
      phone: "0915111222",
      email: "",
    },
    location: {
      provinceCode: "TQ",
      wardCode: "TQ-MB",
      address: "Thôn 13",
      latitude: 21.8452,
      longitude: 105.1824,
    },
    productGroupIds: ["TEA"],
    services: ["DRYING", "ROASTING", "PACKAGING"],
    description:
      "Chế biến chè xanh, chè vàng; nhận gia công sấy chè búp tươi theo mùa vụ.",
    offersExternalCapacity: true,
    machines: [
      machine(
        "m-5",
        "Máy sấy băng tải",
        ["DRYING"],
        ["TEA"],
        45,
        "TON_PER_MONTH",
      ),
    ],
    hasCertification: false,
    certifications: [],
    avatarUrl: "",
    facilityPhotos: [],
    machinePhotos: [],
  },
  // f-4
  {
    name: "Công ty TNHH Một thành viên Chè Phú Bền",
    organizationType: "ENTERPRISE",
    taxCode: "2600110110",
    foundedYear: 1995,
    representative: {
      fullName: "Lê Minh Tuấn",
      gender: "MALE",
      phone: "0983456789",
      email: "",
    },
    location: {
      provinceCode: "PT",
      wardCode: "PT-TB",
      address: "Khu 8, Thanh Ba",
      latitude: 21.4927,
      longitude: 105.1501,
    },
    productGroupIds: ["TEA"],
    services: ["WASHING", "DRYING", "SORTING", "PACKAGING", "STORAGE"],
    description:
      "Nhà máy chè đen CTC công suất lớn, sản phẩm xuất khẩu Trung Đông, Nga. Có kho thành phẩm 3.000 m².",
    offersExternalCapacity: true,
    machines: [
      machine(
        "m-6",
        "Dây chuyền chè đen CTC",
        ["WASHING", "DRYING"],
        ["TEA"],
        300,
        "TON_PER_MONTH",
      ),
      machine(
        "m-7",
        "Kho thành phẩm",
        ["STORAGE"],
        ["TEA"],
        500,
        "TON_PER_MONTH",
      ),
    ],
    hasCertification: true,
    certifications: [
      {
        id: "c-4",
        type: "ISO",
        number: "ISO22000-PT-0877",
        issuedDate: "2024-01-10",
        expiryDate: "2027-01-10",
        issuer: "BV",
      },
      {
        id: "c-5",
        type: "HACCP",
        number: "HACCP-PT-2024-0021",
        issuedDate: "2024-01-10",
        expiryDate: "2027-01-10",
        issuer: "BV",
      },
    ],
    avatarUrl: "",
    facilityPhotos: TEA_PHOTOS,
    machinePhotos: MACHINE_PHOTOS.slice(0, 2),
  },
  // f-5
  {
    name: "Công ty TNHH Một thành viên Traphacosapa",
    organizationType: "ENTERPRISE",
    taxCode: "5300203747",
    foundedYear: 2004,
    representative: {
      fullName: "Lò Thị Mai",
      gender: "FEMALE",
      phone: "0971112233",
      email: "",
    },
    location: {
      provinceCode: "LC",
      wardCode: "LC-SP",
      address: "Tổ 2, phường Sa Pa",
      latitude: 22.3364,
      longitude: 103.8438,
    },
    productGroupIds: ["HERB"],
    services: ["DRYING", "GRINDING", "EXTRACTING", "PACKAGING"],
    description:
      "Trồng và sơ chế dược liệu vùng cao (atiso, đương quy, xuyên khung) theo GACP-WHO, cung ứng nguyên liệu cho Traphaco.",
    offersExternalCapacity: true,
    machines: [
      machine(
        "m-8",
        "Lò sấy dược liệu",
        ["DRYING"],
        ["HERB"],
        15,
        "TON_PER_MONTH",
      ),
      machine(
        "m-9",
        "Máy nghiền bột dược liệu",
        ["GRINDING"],
        ["HERB"],
        6000,
        "KG_PER_MONTH",
        "MAINTENANCE",
      ),
    ],
    hasCertification: true,
    certifications: [
      {
        id: "c-6",
        type: "GMP",
        number: "GACP-WHO-LC-019",
        issuedDate: "2023-06-01",
        expiryDate: "2026-12-01",
        issuer: "VFA",
      },
    ],
    avatarUrl: "",
    facilityPhotos: HERB_PHOTOS,
    machinePhotos: MACHINE_PHOTOS.slice(4, 6),
  },
  // f-6
  {
    name: "Công ty Cổ phần Sản xuất và Xuất khẩu Quế Hồi Việt Nam (Vinasamex)",
    organizationType: "ENTERPRISE",
    taxCode: "0106014027",
    foundedYear: 2012,
    representative: {
      fullName: "Đỗ Thị Hằng",
      gender: "FEMALE",
      phone: "0936222444",
      email: "",
    },
    location: {
      provinceCode: "LC",
      wardCode: "LC-YB",
      address: "Nhà máy chế biến quế, phường Yên Bái",
      latitude: 21.7229,
      longitude: 104.9113,
    },
    productGroupIds: ["SPICE"],
    services: ["DRYING", "PEELING", "GRINDING", "EXTRACTING", "PACKAGING"],
    description:
      "Chế biến quế, hồi xuất khẩu: quế ống, quế chẻ, bột quế và tinh dầu quế. Nguyên liệu từ vùng quế Văn Yên, Trấn Yên.",
    offersExternalCapacity: true,
    machines: [
      machine(
        "m-10",
        "Dây chuyền cạo, cắt quế",
        ["PEELING"],
        ["SPICE"],
        1200,
        "TON_PER_MONTH",
      ),
      machine(
        "m-11",
        "Nồi chưng cất tinh dầu quế",
        ["EXTRACTING"],
        ["SPICE"],
        8,
        "TON_PER_MONTH",
      ),
    ],
    hasCertification: true,
    certifications: [
      {
        id: "c-7",
        type: "ISO",
        number: "ISO22000-YB-2211",
        issuedDate: "2024-04-12",
        expiryDate: "2027-04-12",
        issuer: "SGS",
      },
      {
        id: "c-8",
        type: "OTHER",
        number: "USDA-ORG-VN-0931",
        issuedDate: "2024-09-01",
        expiryDate: "2025-09-01",
        issuer: "OTHER",
      },
    ],
    avatarUrl: "",
    facilityPhotos: HERB_PHOTOS.slice(0, 1),
    machinePhotos: MACHINE_PHOTOS.slice(1, 3),
  },
  // f-7
  {
    name: "Công ty Chè Mộc Châu",
    organizationType: "ENTERPRISE",
    taxCode: "5500154046",
    foundedYear: 1958,
    representative: {
      fullName: "Vũ Đức Long",
      gender: "MALE",
      phone: "0912888999",
      email: "",
    },
    location: {
      provinceCode: "SL",
      wardCode: "SL-MC",
      address: "Tiểu khu 1, Mộc Châu",
      latitude: 20.8474,
      longitude: 104.6355,
    },
    productGroupIds: ["TEA"],
    services: ["WASHING", "DRYING", "ROASTING", "SORTING", "PACKAGING"],
    description:
      "Doanh nghiệp chè lâu đời trên cao nguyên Mộc Châu: chè ô long, chè xanh, matcha; vùng nguyên liệu đạt Rainforest Alliance.",
    offersExternalCapacity: true,
    machines: [
      machine(
        "m-12",
        "Dây chuyền chè ô long",
        ["DRYING", "ROASTING"],
        ["TEA"],
        30,
        "TON_PER_MONTH",
      ),
      machine(
        "m-13",
        "Dây chuyền chè xanh",
        ["WASHING", "DRYING"],
        ["TEA"],
        80,
        "TON_PER_MONTH",
      ),
    ],
    hasCertification: true,
    certifications: [
      {
        id: "c-9",
        type: "HACCP",
        number: "HACCP-SL-2024-0056",
        issuedDate: "2024-02-15",
        expiryDate: "2027-02-15",
        issuer: "VINACERT",
      },
      {
        id: "c-10",
        type: "OTHER",
        number: "RA-VN-SL-2023-14",
        issuedDate: "2023-05-01",
        expiryDate: "2026-11-30",
        issuer: "OTHER",
      },
    ],
    avatarUrl: img("photo-1523920290228-4f321a939b4c", 200),
    facilityPhotos: TEA_PHOTOS,
    machinePhotos: MACHINE_PHOTOS.slice(0, 4),
  },
  // f-8
  {
    name: "Công ty TNHH Chế biến Chè Tân Lập Mộc Châu",
    organizationType: "ENTERPRISE",
    taxCode: "5500281887",
    foundedYear: 2006,
    representative: {
      fullName: "Hà Văn Chiến",
      gender: "MALE",
      phone: "0978333444",
      email: "",
    },
    location: {
      provinceCode: "SL",
      wardCode: "SL-TL",
      address: "Bản Hoa",
      latitude: 20.8752,
      longitude: 104.7216,
    },
    productGroupIds: ["TEA"],
    services: ["DRYING", "PACKAGING"],
    description:
      "Xưởng chè xanh quy mô vừa, thu mua chè búp tươi của hộ dân Tân Lập, Chiềng Sơn.",
    offersExternalCapacity: true,
    machines: [
      machine(
        "m-14",
        "Máy sấy chè xanh",
        ["DRYING"],
        ["TEA"],
        20,
        "TON_PER_MONTH",
      ),
    ],
    hasCertification: true,
    certifications: [
      {
        id: "c-11",
        type: "FOOD_SAFETY",
        number: "12/2023/ATTP-SL",
        issuedDate: "2023-01-05",
        expiryDate: "2026-01-05",
        issuer: "DARD",
      },
    ],
    avatarUrl: "",
    facilityPhotos: [],
    machinePhotos: [],
  },
  // f-9
  {
    name: "Công ty Cổ phần Thực phẩm Xuất khẩu Đồng Giao (Doveco)",
    organizationType: "ENTERPRISE",
    taxCode: "2700224457",
    foundedYear: 1955,
    representative: {
      fullName: "Phạm Thị Thu",
      gender: "FEMALE",
      phone: "0973456123",
      email: "sales@doveco.com.vn",
    },
    location: {
      provinceCode: "NB",
      wardCode: "NB-TD",
      address: "Đường Đồng Giao, tổ dân phố Trại Vòng",
      latitude: 20.1565,
      longitude: 105.9123,
    },
    productGroupIds: ["FRUIT", "VEGETABLE"],
    services: [
      "WASHING",
      "PEELING",
      "PRESSING",
      "FREEZING",
      "BOTTLING",
      "PACKAGING",
      "STORAGE",
    ],
    description:
      "Nhà máy rau quả Doveco Ninh Bình (~32.000 tấn sản phẩm/năm): dứa đóng hộp, nước ép cô đặc, rau quả đông lạnh IQF. Vùng nguyên liệu dứa Đồng Giao.",
    offersExternalCapacity: true,
    machines: [
      machine(
        "m-15",
        "Dây chuyền ép dứa cô đặc",
        ["WASHING", "PEELING", "PRESSING"],
        ["FRUIT"],
        1500,
        "TON_PER_MONTH",
      ),
      machine(
        "m-16",
        "Hầm cấp đông IQF",
        ["FREEZING"],
        ["FRUIT", "VEGETABLE"],
        600,
        "TON_PER_MONTH",
      ),
      machine(
        "m-17",
        "Dây chuyền chiết rót lon",
        ["BOTTLING", "PACKAGING"],
        ["FRUIT"],
        900,
        "TON_PER_MONTH",
      ),
    ],
    hasCertification: true,
    certifications: [
      {
        id: "c-12",
        type: "HACCP",
        number: "HACCP-NB-2024-0156",
        issuedDate: "2024-05-10",
        expiryDate: "2027-05-10",
        issuer: "QUACERT",
      },
      {
        id: "c-13",
        type: "ISO",
        number: "FSSC22000-NB-0342",
        issuedDate: "2023-10-01",
        expiryDate: "2026-10-01",
        issuer: "SGS",
      },
    ],
    avatarUrl: img("photo-1550258987-190a2d41a8ba", 200),
    facilityPhotos: FRUIT_PHOTOS,
    machinePhotos: MACHINE_PHOTOS,
  },
  // f-10
  {
    name: "Công ty Cổ phần Nafoods Group",
    organizationType: "ENTERPRISE",
    taxCode: "2900326375",
    foundedYear: 1995,
    representative: {
      fullName: "Nguyễn Hữu Phúc",
      gender: "MALE",
      phone: "0904567890",
      email: "",
    },
    location: {
      provinceCode: "NA",
      wardCode: "NA-QC",
      address: "Nhà máy Naprod, xã Quỳnh Châu",
      latitude: 19.2201,
      longitude: 105.5832,
    },
    productGroupIds: ["FRUIT"],
    services: ["WASHING", "PRESSING", "FREEZING", "PACKAGING", "STORAGE"],
    description:
      "Chế biến chanh leo, dứa, nhãn: nước cốt, puree đông lạnh, quả IQF xuất khẩu châu Âu. Trụ sở tại 47 Nguyễn Cảnh Hoan, Vinh.",
    offersExternalCapacity: true,
    machines: [
      machine(
        "m-18",
        "Dây chuyền puree chanh leo",
        ["WASHING", "PRESSING"],
        ["FRUIT"],
        800,
        "TON_PER_MONTH",
      ),
      machine(
        "m-19",
        "Kho lạnh âm sâu -18°C",
        ["STORAGE", "FREEZING"],
        ["FRUIT"],
        2000,
        "TON_PER_MONTH",
      ),
    ],
    hasCertification: true,
    certifications: [
      {
        id: "c-14",
        type: "ISO",
        number: "BRC-NA-2024-1182",
        issuedDate: "2024-07-01",
        expiryDate: "2025-07-01",
        issuer: "BV",
      },
      {
        id: "c-15",
        type: "HACCP",
        number: "HACCP-NA-2024-0301",
        issuedDate: "2024-07-01",
        expiryDate: "2027-07-01",
        issuer: "BV",
      },
    ],
    avatarUrl: "",
    facilityPhotos: FRUIT_PHOTOS,
    machinePhotos: MACHINE_PHOTOS.slice(3),
  },
  // f-11
  {
    name: "Công ty TNHH MTV Xuất nhập khẩu 2-9 Đắk Lắk (Simexco Daklak)",
    organizationType: "ENTERPRISE",
    taxCode: "",
    foundedYear: 1993,
    representative: {
      fullName: "Y Blim Niê",
      gender: "MALE",
      phone: "0905123456",
      email: "",
    },
    location: {
      provinceCode: "DLK",
      wardCode: "DLK-BMT",
      address: "23 Ngô Quyền",
      latitude: 12.6797,
      longitude: 108.0441,
    },
    productGroupIds: ["COFFEE", "SPICE"],
    services: ["DRYING", "PEELING", "SORTING", "ROASTING", "STORAGE"],
    description:
      "Chế biến cà phê nhân, hồ tiêu xuất khẩu; hệ thống kho và nhà máy công suất trên 120.000 tấn/năm.",
    offersExternalCapacity: true,
    machines: [
      machine(
        "m-20",
        "Dây chuyền xát, phân loại cà phê",
        ["PEELING", "SORTING"],
        ["COFFEE"],
        6000,
        "TON_PER_MONTH",
      ),
      machine(
        "m-21",
        "Sân phơi + máy sấy tầng sôi",
        ["DRYING"],
        ["COFFEE", "SPICE"],
        2500,
        "TON_PER_MONTH",
      ),
      machine(
        "m-22",
        "Máy rang cà phê",
        ["ROASTING"],
        ["COFFEE"],
        40,
        "TON_PER_MONTH",
      ),
    ],
    hasCertification: true,
    certifications: [
      {
        id: "c-16",
        type: "OTHER",
        number: "4C-VN-DL-0098",
        issuedDate: "2024-03-01",
        expiryDate: "2027-03-01",
        issuer: "OTHER",
      },
      {
        id: "c-17",
        type: "HACCP",
        number: "HACCP-DL-2022-0077",
        issuedDate: "2022-06-01",
        expiryDate: "2025-06-01",
        issuer: "VINACERT",
      },
    ],
    avatarUrl: img("photo-1447933601403-0c6688de566e", 200),
    facilityPhotos: COFFEE_PHOTOS,
    machinePhotos: MACHINE_PHOTOS.slice(0, 3),
  },
  // f-12
  {
    name: "Chi nhánh Công ty CP Tập đoàn Intimex tại Buôn Ma Thuột",
    organizationType: "ENTERPRISE",
    taxCode: "0304421306-002",
    foundedYear: 2008,
    representative: {
      fullName: "Trương Công Minh",
      gender: "MALE",
      phone: "0935678123",
      email: "",
    },
    location: {
      provinceCode: "DLK",
      wardCode: "DLK-TA",
      address: "Lô CN3, Cụm công nghiệp Tân An 2, Km 8 tỉnh lộ 8",
      latitude: 12.7218,
      longitude: 108.0615,
    },
    productGroupIds: ["COFFEE"],
    services: ["SORTING", "ROASTING", "PACKAGING", "STORAGE"],
    description:
      "Nhà máy chế biến cà phê nhân xuất khẩu và cà phê rang xay; nhận gia công đánh bóng, phân loại theo hợp đồng.",
    offersExternalCapacity: true,
    machines: [
      machine(
        "m-23",
        "Máy phân loại màu (color sorter)",
        ["SORTING"],
        ["COFFEE"],
        3000,
        "TON_PER_MONTH",
      ),
      machine(
        "m-24",
        "Kho cà phê nhân",
        ["STORAGE"],
        ["COFFEE"],
        10000,
        "TON_PER_MONTH",
      ),
    ],
    hasCertification: true,
    certifications: [
      {
        id: "c-18",
        type: "ISO",
        number: "ISO9001-DL-5521",
        issuedDate: "2024-02-01",
        expiryDate: "2027-02-01",
        issuer: "TUV",
      },
    ],
    avatarUrl: "",
    facilityPhotos: COFFEE_PHOTOS.slice(0, 2),
    machinePhotos: MACHINE_PHOTOS.slice(2, 5),
  },
  // f-13
  {
    name: "Công ty Cổ phần Chè Lâm Đồng",
    organizationType: "ENTERPRISE",
    taxCode: "5800000103",
    foundedYear: 1976,
    representative: {
      fullName: "Nguyễn Thanh Bình",
      gender: "MALE",
      phone: "0918777666",
      email: "",
    },
    location: {
      provinceCode: "LD",
      wardCode: "LD-BL",
      address: "Phường Bảo Lộc",
      latitude: 11.5479,
      longitude: 107.8077,
    },
    productGroupIds: ["TEA"],
    services: ["DRYING", "ROASTING", "SORTING", "PACKAGING"],
    description:
      "Chè xanh, chè ô long và trà ướp hoa vùng B'Lao; xuất khẩu Đài Loan, Pakistan.",
    offersExternalCapacity: true,
    machines: [
      machine(
        "m-25",
        "Dây chuyền ô long vo viên",
        ["DRYING", "ROASTING"],
        ["TEA"],
        25,
        "TON_PER_MONTH",
      ),
    ],
    hasCertification: true,
    certifications: [
      {
        id: "c-19",
        type: "FOOD_SAFETY",
        number: "31/2024/ATTP-LĐ",
        issuedDate: "2024-05-01",
        expiryDate: "2027-05-01",
        issuer: "DARD",
      },
    ],
    avatarUrl: "",
    facilityPhotos: TEA_PHOTOS.slice(1),
    machinePhotos: [],
  },
  // f-14
  {
    name: "Công ty TNHH Tâm Châu",
    organizationType: "ENTERPRISE",
    taxCode: "5800234888",
    foundedYear: 1995,
    representative: {
      fullName: "Phan Thị Hương",
      gender: "FEMALE",
      phone: "0909333222",
      email: "info.tc@tamchau.com",
    },
    location: {
      provinceCode: "LD",
      wardCode: "LD-LT",
      address: "Thôn 4 (nhà máy chè Tâm Châu)",
      latitude: 11.5051,
      longitude: 107.7302,
    },
    productGroupIds: ["TEA", "COFFEE"],
    services: ["DRYING", "ROASTING", "PACKAGING"],
    description:
      "Nhà máy chè ô long, trà túi lọc và cà phê rang xay; vùng chè Bảo Lâm – Bảo Lộc.",
    offersExternalCapacity: false,
    machines: [
      machine(
        "m-26",
        "Máy đóng gói trà túi lọc",
        ["PACKAGING"],
        ["TEA"],
        12,
        "TON_PER_MONTH",
      ),
    ],
    hasCertification: true,
    certifications: [
      {
        id: "c-20",
        type: "ISO",
        number: "ISO22000-LD-1043",
        issuedDate: "2023-09-01",
        expiryDate: "2026-09-01",
        issuer: "QUACERT",
      },
    ],
    avatarUrl: "",
    facilityPhotos: TEA_PHOTOS.slice(0, 1),
    machinePhotos: [],
  },
  // f-15
  {
    name: "Công ty Cổ phần Thực phẩm Lâm Đồng (Ladofoods)",
    organizationType: "ENTERPRISE",
    taxCode: "5800408245",
    foundedYear: 1999,
    representative: {
      fullName: "Đinh Quang Vinh",
      gender: "MALE",
      phone: "0916552211",
      email: "",
    },
    location: {
      provinceCode: "LD",
      wardCode: "LD-DL",
      address: "31 Ngô Văn Sở",
      latitude: 11.9536,
      longitude: 108.4581,
    },
    productGroupIds: ["FRUIT"],
    services: ["WASHING", "PRESSING", "FERMENTING", "BOTTLING", "LABELING"],
    description:
      "Rượu vang Đà Lạt, nước ép dâu tằm, sim, mác mác. Hầm ủ lên men và dây chuyền chiết chai.",
    offersExternalCapacity: true,
    machines: [
      machine(
        "m-27",
        "Bồn lên men inox",
        ["FERMENTING"],
        ["FRUIT"],
        150,
        "TON_PER_MONTH",
      ),
      machine(
        "m-28",
        "Dây chuyền chiết chai thủy tinh",
        ["BOTTLING", "LABELING"],
        ["FRUIT"],
        120,
        "TON_PER_MONTH",
      ),
    ],
    hasCertification: true,
    certifications: [
      {
        id: "c-21",
        type: "ISO",
        number: "ISO22000-LD-0715",
        issuedDate: "2024-10-01",
        expiryDate: "2027-10-01",
        issuer: "QUACERT",
      },
    ],
    avatarUrl: "",
    facilityPhotos: FRUIT_PHOTOS.slice(0, 2),
    machinePhotos: MACHINE_PHOTOS.slice(4),
  },
  // f-16
  {
    name: "Công ty TNHH Đà Lạt G.A.P",
    organizationType: "ENTERPRISE",
    taxCode: "5800688634",
    foundedYear: 2008,
    representative: {
      fullName: "Lê Văn Cường",
      gender: "MALE",
      phone: "0918234567",
      email: "",
    },
    location: {
      provinceCode: "LD",
      wardCode: "LD-LV",
      address: "Tổ 54B Nguyên Tử Lực",
      latitude: 11.9681,
      longitude: 108.4526,
    },
    productGroupIds: ["VEGETABLE", "FRUIT"],
    services: ["WASHING", "SORTING", "PACKAGING", "STORAGE"],
    description:
      "Rau ăn lá, củ quả và dâu tây đạt GlobalG.A.P; nhà sơ chế lạnh và kho mát 2–5°C cung ứng siêu thị.",
    offersExternalCapacity: true,
    machines: [
      machine(
        "m-29",
        "Dây chuyền rửa, sơ chế rau",
        ["WASHING", "SORTING"],
        ["VEGETABLE"],
        90,
        "TON_PER_MONTH",
      ),
      machine(
        "m-30",
        "Kho mát 2–5°C",
        ["STORAGE"],
        ["VEGETABLE", "FRUIT"],
        150,
        "TON_PER_MONTH",
      ),
    ],
    hasCertification: true,
    certifications: [
      {
        id: "c-22",
        type: "OTHER",
        number: "GGN-4063061234567",
        issuedDate: "2024-12-01",
        expiryDate: "2025-12-01",
        issuer: "OTHER",
      },
      {
        id: "c-23",
        type: "FOOD_SAFETY",
        number: "44/2024/ATTP-LĐ",
        issuedDate: "2024-02-20",
        expiryDate: "2027-02-20",
        issuer: "DARD",
      },
    ],
    avatarUrl: "",
    facilityPhotos: VEG_PHOTOS,
    machinePhotos: MACHINE_PHOTOS.slice(1, 3),
  },
  // f-17
  {
    name: "Công ty Cổ phần Chế biến Thực phẩm Đà Lạt Tự Nhiên",
    organizationType: "ENTERPRISE",
    taxCode: "5800839019",
    foundedYear: 2010,
    representative: {
      fullName: "Võ Thị Lan",
      gender: "FEMALE",
      phone: "0977889900",
      email: "",
    },
    location: {
      provinceCode: "LD",
      wardCode: "LD-PH",
      address: "Thôn Phú Trung",
      latitude: 11.6947,
      longitude: 108.3693,
    },
    productGroupIds: ["FRUIT", "VEGETABLE", "HERB"],
    services: ["WASHING", "DRYING", "PACKAGING"],
    description:
      "Sấy dẻo, sấy lạnh trái cây và rau củ Đà Lạt (hồng, khoai lang, atiso); nhận gia công sấy theo mẻ.",
    offersExternalCapacity: true,
    machines: [
      machine(
        "m-31",
        "Máy sấy lạnh heat-pump",
        ["DRYING"],
        ["FRUIT", "VEGETABLE", "HERB"],
        18,
        "TON_PER_MONTH",
      ),
      machine(
        "m-32",
        "Máy sấy thăng hoa (freeze-dry)",
        ["DRYING"],
        ["FRUIT"],
        3000,
        "KG_PER_MONTH",
      ),
    ],
    hasCertification: false,
    certifications: [],
    avatarUrl: "",
    facilityPhotos: FRUIT_PHOTOS.slice(1),
    machinePhotos: MACHINE_PHOTOS.slice(0, 2),
  },
  // f-18
  {
    name: "Công ty Cổ phần Rau quả Thực phẩm An Giang (Antesco) – Nhà máy Bình Long",
    organizationType: "ENTERPRISE",
    taxCode: "1600230014-009",
    foundedYear: 1985,
    representative: {
      fullName: "Huỳnh Văn Sang",
      gender: "MALE",
      phone: "0918456123",
      email: "antesco@antesco.com",
    },
    location: {
      provinceCode: "AG",
      wardCode: "AG-CP",
      address: "Đường số 2, Lô D, KCN Bình Long",
      latitude: 10.5163,
      longitude: 105.1985,
    },
    productGroupIds: ["VEGETABLE", "FRUIT"],
    services: ["WASHING", "FREEZING", "PACKAGING", "STORAGE"],
    description:
      "Rau quả đông lạnh IQF (đậu nành rau edamame, bắp non, xoài, khóm) xuất khẩu Nhật, Mỹ, EU.",
    offersExternalCapacity: true,
    machines: [
      machine(
        "m-33",
        "Hầm đông IQF băng chuyền",
        ["FREEZING"],
        ["VEGETABLE", "FRUIT"],
        900,
        "TON_PER_MONTH",
      ),
      machine(
        "m-34",
        "Kho lạnh -20°C",
        ["STORAGE"],
        ["VEGETABLE", "FRUIT"],
        3000,
        "TON_PER_MONTH",
      ),
    ],
    hasCertification: true,
    certifications: [
      {
        id: "c-24",
        type: "HACCP",
        number: "HACCP-AG-2024-0098",
        issuedDate: "2024-03-15",
        expiryDate: "2027-03-15",
        issuer: "NAFIQAD",
      },
      {
        id: "c-25",
        type: "ISO",
        number: "BRC-AG-2024-0442",
        issuedDate: "2024-03-15",
        expiryDate: "2025-03-15",
        issuer: "SGS",
      },
    ],
    avatarUrl: "",
    facilityPhotos: VEG_PHOTOS,
    machinePhotos: MACHINE_PHOTOS.slice(3, 6),
  },
  // f-19
  {
    name: "Công ty Cổ phần Tập đoàn Lộc Trời",
    organizationType: "ENTERPRISE",
    taxCode: "1600192619",
    foundedYear: 1993,
    representative: {
      fullName: "Trần Quốc Khánh",
      gender: "MALE",
      phone: "0913456777",
      email: "",
    },
    location: {
      provinceCode: "AG",
      wardCode: "AG-LX",
      address: "23 Hà Hoàng Hổ",
      latitude: 10.3864,
      longitude: 105.4352,
    },
    productGroupIds: ["GRAIN"],
    services: ["DRYING", "PEELING", "SORTING", "PACKAGING", "STORAGE"],
    description:
      "Chuỗi nhà máy sấy – xay xát – lau bóng gạo; bao tiêu lúa theo mô hình cánh đồng lớn ĐBSCL.",
    offersExternalCapacity: true,
    machines: [
      machine(
        "m-35",
        "Tháp sấy lúa",
        ["DRYING"],
        ["GRAIN"],
        12000,
        "TON_PER_MONTH",
      ),
      machine(
        "m-36",
        "Dây chuyền xay xát, lau bóng gạo",
        ["PEELING", "SORTING"],
        ["GRAIN"],
        9000,
        "TON_PER_MONTH",
      ),
    ],
    hasCertification: true,
    certifications: [
      {
        id: "c-26",
        type: "ISO",
        number: "ISO9001-AG-0019",
        issuedDate: "2024-01-01",
        expiryDate: "2027-01-01",
        issuer: "TUV",
      },
      {
        id: "c-27",
        type: "HACCP",
        number: "HACCP-AG-2023-0310",
        issuedDate: "2023-04-01",
        expiryDate: "2026-04-01",
        issuer: "QUACERT",
      },
    ],
    avatarUrl: img("photo-1586201375761-83865001e31c", 200),
    facilityPhotos: GRAIN_PHOTOS,
    machinePhotos: MACHINE_PHOTOS.slice(0, 3),
  },
  // f-20
  {
    name: "Công ty Cổ phần Nông nghiệp Công nghệ cao Trung An",
    organizationType: "ENTERPRISE",
    taxCode: "1800241736",
    foundedYear: 1996,
    representative: {
      fullName: "Phạm Văn Lợi",
      gender: "MALE",
      phone: "0939123789",
      email: "",
    },
    location: {
      provinceCode: "CT",
      wardCode: "CT-TK",
      address: "649A Quốc lộ 91, khu vực Qui Thạnh 1",
      latitude: 10.2694,
      longitude: 105.5384,
    },
    productGroupIds: ["GRAIN"],
    services: ["DRYING", "PEELING", "SORTING", "PACKAGING", "STORAGE"],
    description:
      "Nhà máy chế biến gạo xuất khẩu (ST25, Jasmine, gạo hữu cơ); kho chứa và dây chuyền đóng bao tự động.",
    offersExternalCapacity: true,
    machines: [
      machine(
        "m-37",
        "Dây chuyền xát trắng, tách màu",
        ["PEELING", "SORTING"],
        ["GRAIN"],
        6000,
        "TON_PER_MONTH",
      ),
      machine(
        "m-38",
        "Máy đóng bao tự động",
        ["PACKAGING"],
        ["GRAIN"],
        4500,
        "TON_PER_MONTH",
        "PAUSED",
      ),
    ],
    hasCertification: true,
    certifications: [
      {
        id: "c-28",
        type: "OTHER",
        number: "EU-ORG-VN-CT-0021",
        issuedDate: "2024-06-01",
        expiryDate: "2026-12-31",
        issuer: "OTHER",
      },
    ],
    avatarUrl: "",
    facilityPhotos: GRAIN_PHOTOS,
    machinePhotos: MACHINE_PHOTOS.slice(2, 4),
  },
];
